name: workflow

on:
  pull_request:
    branches: [main]

jobs:
  connect-remote:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: "%"
          POSTGRES_PASSWORD: "admin123"
          POSTGRES_DB: "assignment1_db"
        ports:
          - 8080:8080
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s 
          --health-retries 3

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.17.1
      - name: create and configure
        run: |
          touch .env
          echo port=8080 >> .env
          echo host=localhost >> .env
          echo dialect=postgres >> .env
          echo user=postgres >> .env
          echo password=admin123 >> .env
          echo database=assignment1_db >> .env
      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test